In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [2]:
df = pd.read_csv("HousingData.csv")
print(df.isnull().sum())
df = df.dropna()

CRIM       20
ZN         20
INDUS      20
CHAS       20
NOX         0
RM          0
AGE        20
DIS         0
RAD         0
TAX         0
PTRATIO     0
B           0
LSTAT      20
MEDV        0
dtype: int64

In [3]:
print(df.isnull().sum())

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

In [4]:
x=df[['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT',]]
y=df[['MEDV']]

In [5]:
df.shape

(394, 14)

In [6]:
x

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94
5,0.02985,0.0,2.18,0.0,0.458,6.430,58.7,6.0622,3,222,18.7,394.12,5.21
...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,0.17783,0.0,9.69,0.0,0.585,5.569,73.5,2.3999,6,391,19.2,395.77,15.10
500,0.22438,0.0,9.69,0.0,0.585,6.027,79.7,2.4982,6,391,19.2,396.90,14.33
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48

In [7]:
y

     MEDV
0    24.0
1    21.6
2    34.7
3    33.4
5    28.7
..    ...
499  17.5
500  16.8
502  20.6
503  23.9
504  22.0

[394 rows x 1 columns]

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

In [9]:
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [10]:
y_pred = model.predict(x_test)

In [11]:
y_pred

array([[29.40315823],
       [17.32130164],
       [21.88438126],
       [30.53897078],
       [18.74211111],
       [34.49957016],
       [22.18772843],
       [30.40016057],
       [33.30285959],
       [15.07065834],
       [22.15266803],
       [40.7986985 ],
       [21.81856333],
       [16.57492925],
       [19.06901469],
       [20.36048341],
       [17.0094124 ],
       [15.281753  ],
       [22.57233525],
       [14.31888726],
       [18.48367439],
       [20.59950781],
       [17.02508296],
       [29.32482063],
       [26.16559295],
       [16.14119305],
       [27.05876571],
       [31.80271449],
       [22.91935834],
       [27.06461644],
       [40.9285908 ],
       [18.23395575],
       [22.32757596],
       [17.40043581],
       [17.75100984],
       [21.14924374],
       [22.00396948],
       [21.66088774],
       [23.1598697 ],
       [20.86075164],
       [27.6556627 ],
       [34.50415574],
       [22.12517086],
       [30.76421403],
       [34.86183582],
       [19.95497559],
       [24.94727208],
       [10.54144025],
       [19.61633902],
       [25.25533113],
       [21.82692573],
       [26.1224415 ],
       [14.58753912],
       [18.60907444],
       [18.73269469],
       [23.877063  ],
       [43.39153407],
       [22.4868859 ],
       [15.58046183],
       [23.42839246],
       [21.35028809],
       [21.41783737],
       [14.59575339],
       [28.83213251],
       [-3.15989071],
       [32.30293312],
       [16.84715194],
       [31.11268272],
       [24.82335627],
       [19.94867799],
       [31.74110086],
       [32.10741168],
       [19.29684222],
       [19.39763513],
       [19.26122628],
       [35.15713713],
       [19.27819376],
       [28.30029199],
       [16.64597387],
       [16.86726667],
       [36.9666121 ],
       [23.88353751],
       [24.02647044],
       [12.90795354],
       [28.61288195],
       [20.95440577],
       [15.33870473],
       [12.28771055],
       [38.47633494],
       [37.07379058],
       [20.50728689],
       [18.65066319],
       [27.44199919],
       [16.08244976],
       [26.83793964],
       [38.72160447],
       [30.53333731],
       [22.90723493],
       [21.57563759]])

In [12]:
model.score(x_train,y_train)

0.7894375551691273

In [13]:
model.score(x_test,y_test)

0.683039107021929

In [14]:
np.sqrt(mean_squared_error(y_test,y_pred))

np.float64(5.457269439843607)